"""Pure classification for a local ledger-versus-Google projection audit.

Callers obtain local ``LedgerProvenance`` records from their own append-only
ledger adapter, load non-secret provenance outbox records, and obtain the
receiver inventory through ``read_reconciliation_inventory_v2``.  This module
never opens files, calls a network, creates incident records, or repairs data.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Iterable, Mapping

from .ledger_integrity import LedgerProvenance, ProjectionClassification, comparison_for


@dataclass(frozen=True)
class ReconciliationFinding:
    trade_id: str
    event_type: str
    classification: ProjectionClassification
    detail: str
    outbox_status: str | None


def _outbox_statuses(records: Iterable[Mapping[str, Any]]) -> dict[tuple[str, str, str], str]:
    """Return the last non-secret lifecycle state for each ledger proof."""
    result: dict[tuple[str, str, str], str] = {}
    for record in records:
        if not isinstance(record, Mapping):
            continue
        trade_id = record.get("trade_id")
        event_type = record.get("event_type")
        payload_digest = record.get("payload_digest")
        status = record.get("status")
        if all(isinstance(value, str) and value for value in (trade_id, event_type, payload_digest, status)):
            result[(trade_id, event_type, payload_digest)] = status
    return result


def classify_projection_inventory(
    *,
    local_provenances: Iterable[LedgerProvenance],
    outbox_records: Iterable[Mapping[str, Any]],
    receiver_items: Iterable[Mapping[str, Any]],
) -> tuple[ReconciliationFinding, ...]:
    """Classify source/projection agreement without mutating either side.

    ``receiver_items`` is intentionally a constrained inventory generated by
    the v2 receiver: one trade ID, Google row count, and receiver audit entries.
    This lets a strategy detect legacy/no-source rows (including historical
    DRY_RUN examples) without granting arbitrary spreadsheet read access.
    """
    local = tuple(local_provenances)
    outbox = _outbox_statuses(outbox_records)
    items_by_trade: dict[str, Mapping[str, Any]] = {}
    for item in receiver_items:
        trade_id = item.get("trade_id") if isinstance(item, Mapping) else None
        if isinstance(trade_id, str) and trade_id:
            items_by_trade[trade_id] = item

    findings: list[ReconciliationFinding] = []
    local_trade_ids = {proof.trade_id for proof in local}
    for proof in local:
        item = items_by_trade.get(proof.trade_id, {})
        audit = item.get("audit", []) if isinstance(item, Mapping) else []
        matching = [row for row in audit if isinstance(row, Mapping) and row.get("event_type") == proof.event_type]
        confirmed = [row.get("payload_digest") for row in matching if row.get("status") == "CONFIRMED" and isinstance(row.get("payload_digest"), str)]
        rejected = any(row.get("status") == "REJECTED" for row in matching)
        count = item.get("google_row_count", 0) if isinstance(item, Mapping) else 0
        if not isinstance(count, int) or count < 0:
            count = 0
        comparison = comparison_for(
            trade_id=proof.trade_id,
            local_payload_digest=proof.payload_digest,
            google_payload_digests=confirmed,
            receiver_rejected=rejected,
        )
        if count > 1:
            comparison = comparison_for(
                trade_id=proof.trade_id,
                local_payload_digest=proof.payload_digest,
                google_payload_digests=[proof.payload_digest, proof.payload_digest],
            )
        findings.append(ReconciliationFinding(
            trade_id=proof.trade_id,
            event_type=proof.event_type,
            classification=comparison.classification,
            detail=comparison.detail,
            outbox_status=outbox.get((proof.trade_id, proof.event_type, proof.payload_digest)),
        ))

    for trade_id, item in sorted(items_by_trade.items()):
        if trade_id in local_trade_ids:
            continue
        count = item.get("google_row_count", 0) if isinstance(item, Mapping) else 0
        if not isinstance(count, int) or count <= 0:
            continue
        findings.append(ReconciliationFinding(
            trade_id=trade_id,
            event_type="unknown",
            classification=ProjectionClassification.GOOGLE_NO_LEDGER_SOURCE,
            detail="Google trade ID has no local append-only ledger provenance",
            outbox_status=None,
        ))
    return tuple(findings)


__all__ = ["ReconciliationFinding", "classify_projection_inventory"]
